In [6]:
import numpy as np

In [7]:
my_list = [1,2,3]

In [8]:
type(my_list)

list

In [10]:
myarray =  np.array(my_list)

In [11]:
myarray

array([1, 2, 3])

In [12]:
type(myarray)

numpy.ndarray

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.zeros(shape=(5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones(shape=(3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
np.zeros((5,5)) #np.ones((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.random.seed(101)

In [44]:
arr = np.random.randint(0,100,10)

In [45]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [46]:
arr2 = np.random.randint(0,100,10)

In [47]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [48]:
arr.max()

95

In [49]:
arr.min()

9

In [50]:
arr.argmax()

0

In [51]:
arr.argmin()

7

In [52]:
arr.mean()

60.8

In [53]:
arr.shape

(10,)

In [54]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [55]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [56]:
met = np.arange(0,100).reshape(10,10)

In [57]:
met

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
row = 0
col =1
met[4][6]

46

In [82]:
met[:,1] #all data in col 1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [83]:
met[:,1].shape

(10,)

In [84]:
met[:,1].reshape((10,1))

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [85]:
met[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
met[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [88]:
met[0:3,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [89]:
met[:,3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [90]:
met[:,3:5] = 0

In [91]:
met

array([[ 0,  1,  2,  0,  0,  5,  6,  7,  8,  9],
       [10, 11, 12,  0,  0, 15, 16, 17, 18, 19],
       [20, 21, 22,  0,  0, 25, 26, 27, 28, 29],
       [30, 31, 32,  0,  0, 35, 36, 37, 38, 39],
       [40, 41, 42,  0,  0, 45, 46, 47, 48, 49],
       [50, 51, 52,  0,  0, 55, 56, 57, 58, 59],
       [60, 61, 62,  0,  0, 65, 66, 67, 68, 69],
       [70, 71, 72,  0,  0, 75, 76, 77, 78, 79],
       [80, 81, 82,  0,  0, 85, 86, 87, 88, 89],
       [90, 91, 92,  0,  0, 95, 96, 97, 98, 99]])

In [92]:
mynewmet = met.copy()

In [93]:
mynewmet[0:6,:] = 67

In [94]:
mynewmet

array([[67, 67, 67, 67, 67, 67, 67, 67, 67, 67],
       [67, 67, 67, 67, 67, 67, 67, 67, 67, 67],
       [67, 67, 67, 67, 67, 67, 67, 67, 67, 67],
       [67, 67, 67, 67, 67, 67, 67, 67, 67, 67],
       [67, 67, 67, 67, 67, 67, 67, 67, 67, 67],
       [67, 67, 67, 67, 67, 67, 67, 67, 67, 67],
       [60, 61, 62,  0,  0, 65, 66, 67, 68, 69],
       [70, 71, 72,  0,  0, 75, 76, 77, 78, 79],
       [80, 81, 82,  0,  0, 85, 86, 87, 88, 89],
       [90, 91, 92,  0,  0, 95, 96, 97, 98, 99]])